import sqlite3

connection = sqlite3.connect('etd_back_020722_3PM.db')
cursor = connection.cursor()

""" Using fetchall results in retrieving multiple records for some ETDs. 
Currently using fetchone """

cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m54b9f4n';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5k70z0n';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5nw5z2m';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5m6804v';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5w44976';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5wt5749';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5kd8brt';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5257z2v';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m58w9t5d';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5jf19kj';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5cc7dkt';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5006g0f';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5dv7ztq';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5cp3hsb';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5cw0xkj';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5zd4gst';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m59w6vb7';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5j456c1';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m53g13g1';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m58m3pz1';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m51k5qm6';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5xd7fkj';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m56t71h9';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m55r18x9';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5xt288p';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5cs2762';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5s24gdw';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5dr987j';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5897ksz';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5pp5kh4';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5f82sdt';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5q01pn2';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5qp2mkm';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5p90rtj';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5sz2t2r';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5c3198h';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5771v5x';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5j16h22';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5577rwr';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m51k5qkr';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5kh727f';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m53268sw';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m53c2d18';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5g5145q';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5908hmg';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5vt861c';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5wt575r';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m52z7kdq';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5811gjj';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m54r47sx';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5kt35fz';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5gv221c';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m52g42c3';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5rk0zb4';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5x701rf';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m50w4spb';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5h4859j';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m53z4mkj';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m57h7zcw';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5gf77d4';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5rn9np0';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5n93qnq';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m50k8pgt';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5200j69';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m54b9f53';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5b05jrv';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5tr2fb1';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5bg92vr';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5v18jnn';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5hj2zv3';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m57q5c98';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m53r76p0';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5674t20';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m58h50kj';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5fr69hq';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5mw8wz8';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m57d9829';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5937716';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m59h21pg';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m52s05j5';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5q87sxx';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5sc0knv';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5fc1gr7';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m53n8hbk';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5zq0m16';")
print(cursor.fetchone())
cursor.execute("select * from escholfeed where merritt_ark like 'ark:/13030/m5t21hkq';")
print(cursor.fetchone())

connection.close()

